### ISSUE TITLE
Implement correct config input validation

### ISSUE THREAD

**Issue by m4ng0squ4sh** [bigeagle/gohop#20]
Please implement correct config input validation!

Sample: `addr = 192.168.5.50`

```
gohop -debug -config server.ini
[16-10-02 02:44:41][INFO] using config file: %v server.ini
[16-10-02 02:44:41][DEBUG] %v {4000 4000  192.168.5.50 1400 ilovethebigbrother true none 60  }
[16-10-02 02:44:41][DEBUG] %v {4000 4000  192.168.5.50 1400 ilovethebigbrother true none 60  }
[16-10-02 02:44:41][INFO] interface %v created tun0
[16-10-02 02:44:41][INFO] ip %s link set dev tun0 up mtu 1400 qlen 100
[16-10-02 02:44:41][DEBUG] %v <nil>
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5ac6c0, 0xc4200120e0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/bigeagle/gohop/hop.setTunIP(0xc420015b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6a8920)
	/go/src/github.com/bigeagle/gohop/hop/iface.go:64 +0x97a
github.com/bigeagle/gohop/hop.NewServer(0xfa0, 0xfa0, 0x0, 0x0, 0xc420013640, 0xc, 0x578, 0xc420011120, 0x12, 0x1, ...)
	/go/src/github.com/bigeagle/gohop/hop/server.go:105 +0x52f
main.main()
	/go/src/github.com/bigeagle/gohop/main.go:75 +0x696

```

**Comment by themester** [comment]
Can you give me more information about your problem? In which circumstances occurs?
